import React from "react";
import { Link } from "wouter";
import { StarField } from "../components/StarField";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { FileText, ArrowLeft, Shield } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="relative min-h-screen bg-black text-zinc-100 overflow-x-hidden">
      {/* Background Starfield effect */}
      <div className="fixed inset-0 z-0 opacity-40">
        <StarField />
      </div>

      {/* Decorative Glows */}
      <div className="fixed top-0 left-1/2 -translate-x-1/2 w-[600px] h-[300px] bg-[radial-gradient(circle_at_center,rgba(212,163,62,0.1)_0%,transparent_70%)] blur-3xl z-0 pointer-events-none" />

      <div className="relative z-10 max-w-4xl mx-auto px-4 py-12 sm:py-16">
        {/* Brand Header */}
        <div className="flex items-center justify-center mb-8">
          <span className="text-xl font-extrabold tracking-widest bg-gradient-to-r from-amber-200 via-amber-400 to-amber-500 bg-clip-text text-transparent">
            GG33 CORE
          </span>
        </div>

        <Card className="bg-zinc-950/80 border-zinc-800/80 backdrop-blur-xl shadow-2xl">
          <CardHeader className="space-y-2 border-b border-zinc-800/80 pb-6">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-amber-500/10 border border-amber-500/30 flex items-center justify-center">
                <FileText className="w-5 h-5 text-amber-400" />
              </div>
              <div>
                <CardTitle className="text-2xl sm:text-3xl font-extrabold text-zinc-100">
                  Terms of Service
                </CardTitle>
                <CardDescription className="text-xs sm:text-sm text-zinc-400 mt-1">
                  Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
                </CardDescription>
              </div>
            </div>
          </CardHeader>

          <CardContent className="p-6 sm:p-8 space-y-8 text-sm leading-relaxed text-zinc-300">
            <section className="space-y-3">
              <h3 className="text-base font-bold text-zinc-100 flex items-center gap-2">
                <span className="text-amber-400">1.</span> Acceptance of Terms
              </h3>
              <p>
                By registering for, accessing, or using GG33 CORE ("Service"), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must not use our service.
              </p>
            </section>

            <section className="space-y-3">
              <h3 className="text-base font-bold text-zinc-100 flex items-center gap-2">
                <span className="text-amber-400">2.</span> Service Description & Disclaimer
              </h3>
              <p>
                GG33 CORE provides numerological calculations, astrological algorithms, energy pattern analysis, educational content, and AI-assisted insights. All content and readings generated by the platform are intended for personal insight, educational, and entertainment purposes only. They do not constitute financial, legal, medical, or professional advice.
              </p>
            </section>

            <section className="space-y-3">
              <h3 className="text-base font-bold text-zinc-100 flex items-center gap-2">
                <span className="text-amber-400">3.</span> Subscriptions, Billing & Cancellations
              </h3>
              <p>
                Certain features (including the Cues Database, unlimited AI CueChats, full Study Zone courses, and comprehensive Explore insights) require an active GG33 Pro subscription. Subscriptions are billed on a recurring monthly basis through Whop Payments.
              </p>
              <p>
                You may cancel your subscription at any time directly through the in-app subscription manager or via the Whop Customer Portal (https://whop.com/hub/). Cancellation takes effect immediately upon confirmation.
              </p>
            </section>

            <section className="space-y-3">
              <h3 className="text-base font-bold text-zinc-100 flex items-center gap-2">
                <span className="text-amber-400">4.</span> User Accounts & Security
              </h3>
              <p>
                You must provide accurate information when creating an account. You are responsible for safeguarding your login credentials and are solely responsible for all activities that occur under your account.
              </p>
            </section>

            <section className="space-y-3">
              <h3 className="text-base font-bold text-zinc-100 flex items-center gap-2">
                <span className="text-amber-400">5.</span> Intellectual Property
              </h3>
              <p>
                The GG33 numerology system, proprietary formulas, interface designs, text, graphics, and trademarks are the intellectual property of GG33 CORE. You may not copy, scrape, reproduce, or redistribute any platform content without prior written permission.
              </p>
            </section>

            <section className="space-y-3">
              <h3 className="text-base font-bold text-zinc-100 flex items-center gap-2">
                <span className="text-amber-400">6.</span> Limitation of Liability
              </h3>
              <p>
                Under no circumstances shall GG33 CORE, its creators, affiliates, or licensors be liable for any direct, indirect, incidental, consequential, or exemplary damages resulting from your use of or inability to use the platform.
              </p>
            </section>

            <section className="space-y-3">
              <h3 className="text-base font-bold text-zinc-100 flex items-center gap-2">
                <span className="text-amber-400">7.</span> Contact Information
              </h3>
              <p>
                For questions regarding these Terms of Service, please contact our support team through the official GG33 platform channels.
              </p>
            </section>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
